### ISSUE TITLE
Formatting in Report configuration

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#11]
For example, go to Reports > Contact Reports > Activity Details > Filters and set Activity Status to Completed

![Screenshot from 2021-01-08 11-41-41](https://user-images.githubusercontent.com/2730045/104011756-90299f80-51a6-11eb-8284-bf8e174b139f.png)

This seems to affect all 'Is one of' fields.

Also, the operator 'Contains', 'Is one of' etc has the drop down selector and works but does not have visual indication that it can be changed.

**Comment by vingle** [comment]
I seem to have closed this issue, maybe by using the word 'close' in my commit message! Reopening but the last commit should have fixed this.

**Comment by vingle** [comment]
Closing as I can no longer replicate this.

**Comment by aydun** [comment]
Eventually got round to testing this.  Yes, this fixes it. Thanks!
