### ISSUE TITLE
SearchKit - TH borders and italic icons

### ISSUE THREAD

**Issue by colemanw** [vingle/finsburypark#14]
This is SearchKit on FinsburyPark & the Drupal Seven theme. The table headers have an odd border on the left, and icons are <i>ITALIC!</i>

![image](https://user-images.githubusercontent.com/2874912/107542609-5decd280-6b96-11eb-9c2b-d684be025816.png)

**Comment by vingle** [comment]
Not quite sure how that `<i>` bug lasted so long but it's just removed. Table header border seems like a Seven clash as not present in J! But I've seen those dotted lines elsewhere in` <th>`, will investigate.

**Comment by colemanw** [comment]
Thanks. That fixed the icons. The border appears to be coming from here: https://github.com/vingle/finsburypark/blob/ed6e012f072b0176e0370cf2081d6cb0f9ea1649/css/civicrm.css#L526-L528

**Comment by vingle** [comment]
Thanks - and that sometimes seems to be overriding this, and sometimes not:

https://github.com/vingle/finsburypark/blob/ed6e012f072b0176e0370cf2081d6cb0f9ea1649/css/civicrm.css#L447-L450

all my table css seems to repeat itself a lot. I've hardly stripped any from the old civicrm.css as I couldn't guess what would break so just added my styling. Would be nice to just take it all out and start again.

**Comment by vingle** [comment]
The dotted `th` should be removed in the latest version on master https://github.com/vingle/finsburypark/blob/f3a5901e082c16c84e2d1e32989115a03349083c/css/bootstrap3.css#L25

**Comment by vingle** [comment]
Did the latest release fix this for you @colemanw?
