### ISSUE TITLE
Display preferences page

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#20]
Not sure about this one... There is interaction between the Civi theme and the CRM theme.  On this site, it's using Drupal 7 with Adminimal.  I'm experimenting with a few colour changes but otherwise it's looking ok.

However, the Display Preferences page looks like this:
![Screenshot from 2021-03-11 16-06-10](https://user-images.githubusercontent.com/2730045/110834059-ff01a280-8294-11eb-80a5-a2f985183498.png)

It is ok with Seven instead of Adminimal:
![Screenshot from 2021-03-11 18-11-01](https://user-images.githubusercontent.com/2730045/110834232-34a68b80-8295-11eb-8ada-3cbafd28f948.png)

So Q1 - is Adminimal within scope?  Q2 - if yes, can we fix this?

**Comment by vingle** [comment]
1. I've not tried it on Adminimal.. so technically no but it'd be good to resolve. out of interest - how does this page look with Grenwich + Adminimal?
2. At a guess, it could be that changing some of the relevent selectors here, ie `.crm-container ul.crm-checkbox-list li input` to start with `#crm-container` could push them up the cascade higher than whatever in Adminimal is causing the problem here.

**Comment by aydun** [comment]
Here's Greenwich + Adminimal:
![Screenshot from 2021-03-12 10-10-29](https://user-images.githubusercontent.com/2730045/110925641-5d716400-831b-11eb-835e-128aac0bb2a1.png)

**Comment by aydun** [comment]
Good guess!  Implementing 2) as you suggested results in this (Adminimal + FP edited)
![Screenshot from 2021-03-12 10-38-34](https://user-images.githubusercontent.com/2730045/110928791-2ef58800-831f-11eb-8f38-0d0c08b0cfbe.png)

There is a further issue with the 'Contact Details' and 'Other Panes' blocks but may be easier to discuss that.

**Comment by vingle** [comment]
I have Christian Wach to thank for suggesting it as way round using !important so often to override civi's base css (and pointing me to the brilliant https://cssspecificity.com/ resource).

**Comment by vingle** [comment]
Should be fixed for Adminimal in v0.12.

**Comment by vingle** [comment]
Can I close this @aydun?

**Comment by aydun** [comment]
Yes, looks good - thanks.
