### ISSUE TITLE
Transparent background and hidden buttons on some pop-ups

### ISSUE THREAD

**Issue by herbdool** [vingle/finsburypark#27]
I'm seeing hidden buttons (need to scroll down):

![2022-04-21 15 37 51 xmass lndo site b8512063ac96](https://user-images.githubusercontent.com/1071483/164540632-d3a6f774-05f5-4898-a237-6ababe34ea22.png)

and transparent backgrounds:

![2022-04-21 15 33 58 xmass lndo site 24b661778154](https://user-images.githubusercontent.com/1071483/164539718-60f089ba-37e3-43fc-8f6c-53db91d0bb94.png)

I'm using the theme on Drupal 9.

**Comment by herbdool** [comment]
I should add that I had enabled the CiviCRM Administration UI extension on 5.48.* so not sure if that is conflicting.

**Comment by vingle** [comment]
To check @herbdool , is this v0.13 from Github or [v0.15 from the more recent Gitlab distro](https://lab.civicrm.org/extensions/finsburypark)?

**Comment by herbdool** [comment]
Oh, it's the 0.15 version from gitlab. I can copy my issue there if that helps.

**Comment by vingle** [comment]
Thanks for reporting - I can see a bunch of issues with 5.48, I'd not tested against that yet. Will look at this as soon as I can.

**Comment by vingle** [comment]
I think this is now fixed in the [latest version](https://lab.civicrm.org/extensions/finsburypark).

**Comment by herbdool** [comment]
Thanks! I'll be able to try it soon.
