### ISSUE TITLE
Extensions page - can't expand

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#6]
At /civicrm/admin/extensions (Drupal 7), the extensions are listed but you can't expand them to see details.

**Comment by vingle** [comment]
Are you definitely using the latest version as this *was* a bug but it got fixed a few versions back?

**Comment by vingle** [comment]
I've just double checked v0.7 on Drupal and it should be fine. But this was an issue [in any earlier version](https://github.com/vingle/st.visuali.finsburypark/commit/d3a213559bb7685b2b5579155f9edad0dd75e4e3) after the accordian triangle image sprites were replaced with FontAwesome in Civi core over the summer.

**Comment by aydun** [comment]
Thanks!  My git remote was set to lab rather than github and github is ahead of lab.  Now that I've got the updated version the problem is fixed.

That also explains why I couldn't find the issues I created previously - they are on lab, not github.

**Comment by vingle** [comment]
Ah! Sorry. I feel that updating Lab from Hub should be really easy but my git skills are so rusty and rarely practiced I need a cup of tea and a clear hour or so!

**Comment by aydun** [comment]
I think it's supposed to be easy - but I've not tried it...
