### ISSUE TITLE
Viewing activities - duplicate buttons

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#7]
Go to a contact, select activity tab, view an activity - there are duplicate buttons at the bottom:

![Screenshot from 2020-12-23 18-24-48](https://user-images.githubusercontent.com/2730045/103026798-8f5d0080-454c-11eb-8fbd-4ee8c62cc069.png)

and similar with 'edit' and contributions, notes - maybe other entities

**Comment by vingle** [comment]
Hmm.. that's a curious one. If I load Grenwich, they also show the dupe buttons, but they're outside of the div with `overflow:hidden` (which you can see unset like below). Can't say I understand, but I can recreate what Grenwich does.

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/1175967/103028098-faa7d200-454e-11eb-903e-8cb22185047a.png">

**Comment by vingle** [comment]
This should be fixed in the latest v0.8 release, sorry for the delay.

**Comment by aydun** [comment]
Great!  That fixes it - many thanks.
