### ISSUE TITLE
New contact form top button spacing

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#8]
Go to New Individual (or Org/HH), the top buttons overlap the accordion:
![Screenshot from 2021-01-04 18-46-06](https://user-images.githubusercontent.com/2730045/103568407-637f3a80-4ebd-11eb-8439-bfeb17102dd9.png)

**Comment by vingle** [comment]
I couldn't recreate this on Joomla, but can see it on D7, latest update should have fixed it.

**Comment by aydun** [comment]
Lovely!
